# Generated by Django 3.2.18 on 2023-05-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
